"""empty message

Revision ID: 12f836b88a66
Revises: fa0eaa8e9404
Create Date: 2017-10-25 16:04:21.154417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12f836b88a66'
down_revision = 'fa0eaa8e9404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designs', sa.Column('design', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('designs', 'design')
    # ### end Alembic commands ###
