"""empty message

Revision ID: fa0eaa8e9404
Revises: 29d76eb2a7c3
Create Date: 2017-10-21 18:55:47.705603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0eaa8e9404'
down_revision = '29d76eb2a7c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designs', sa.Column('timeCreated', sa.DateTime(), nullable=True))
    op.add_column('designs', sa.Column('timeLastUpdated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('designs', 'timeLastUpdated')
    op.drop_column('designs', 'timeCreated')
    # ### end Alembic commands ###
